In [1]:
from generator import Generator
from keras.callbacks import CSVLogger
from keras.callbacks import ModelCheckpoint
from keras.callbacks import ReduceLROnPlateau
from models import NIC
from data_manager import DataManager
from keras.utils import plot_model
import tensorflow as tf
from keras.backend.tensorflow_backend import set_session
import matplotlib.pyplot as plt

/home/eric/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
num_epochs = 125
batch_size = 128
cnn_extractor='inception'
object_image_features_filename='inception_image_name_to_features.h5'

In [3]:
root_path = '../../datasets/image_text/'
captions_filename = root_path + 'image_text_data.txt'
data_manager = DataManager(data_filename=captions_filename,
                            max_caption_length=20,
                            word_frequency_threshold=2,
                            extract_image_features=False,
                            cnn_extractor=cnn_extractor,
                            image_directory=root_path,
                            split_data=True,
                            dump_path=root_path + 'preprocessed_data/')

In [4]:
data_manager.preprocess()
print(data_manager.captions[0])
print(data_manager.word_frequencies[0:20])

preprocessed_data_path = root_path + 'preprocessed_data/'
generator = Generator(data_path=preprocessed_data_path,
                      batch_size=batch_size,image_features_filename=object_image_features_filename)


Loading data ...
Loaded 57177 captions
Removing captions longer than 20 ...
Number of files removed: 11399
Current number of files: 45778
Removing words with a frequency less than 2 ...
Number of words removed: 1
Current number of words: 997
num of training data size: 41200
num of validation data size: 4578
['likeforlikes', 'follows', 'lgbt', 'gay', 'instafollow', 'tbt', 'follow', 'followfollow', 'likelike', 'look', 'tumblr', 'video', 'photo', 'makeup']
[['love' '7949']
 ['instagood' '5879']
 ['christmas' '4826']
 ['photography' '4814']
 ['art' '4524']
 ['photooftheday' '4345']
 ['fashion' '3911']
 ['fitness' '3522']
 ['picoftheday' '3077']
 ['beautiful' '3064']
 ['travel' '3059']
 ['instagram' '2836']
 ['happy' '2810']
 ['food' '2683']
 ['style' '2512']
 ['nature' '2492']
 ['cute' '2489']
 ['motivation' '2446']
 ['beauty' '2349']
 ['family' '2164']]
Loading training dataset...
Loading validation dataset...
Loading all tweet dataset...
Loading vocabulary...


In [5]:
num_training_samples =  generator.training_dataset.shape[0]
num_validation_samples = generator.validation_dataset.shape[0]
print('Number of training samples:', num_training_samples)
print('Number of validation samples:', num_validation_samples)

print(generator.VOCABULARY_SIZE)
print(generator.IMG_FEATS)

Number of training samples: 41200
Number of validation samples: 4578
1000
2048


In [6]:
train_gen=generator.flow(mode='train')
print(train_gen)

<generator object Generator.flow at 0x7fb3fd405410>


In [7]:
batch=next(train_gen)
print(batch[0]['image'].shape)
print(batch[0]['text'].shape)
print(batch[0]['tweet'].shape)

(128, 22, 2048)
(128, 22, 1000)
(128, 80)


In [10]:
print(batch[0]['tweet'])

[[0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 ... 7.700e+01 1.261e+03 8.280e+02]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 3.840e+02]
 ...
 [0.000e+00 0.000e+00 0.000e+00 ... 1.000e+00 1.831e+03 3.400e+02]
 [0.000e+00 0.000e+00 0.000e+00 ... 2.000e+00 9.000e+00 2.300e+02]
 [0.000e+00 0.000e+00 0.000e+00 ... 1.713e+03 1.300e+02 1.020e+02]]
